filter:
  excluded_paths:
    - vendor/*

build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
          - phpcs-run --extensions=php --standard=PSR2

tools:
  external_code_coverage: true
