language: php

php:
  - 7.1
  - 7.2
  - 7.3

env:
  - SYMFONY_VERSION=4.2.*
  - SYMFONY_VERSION=4.3.*

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer require symfony/symfony:${SYMFONY_VERSION}

script:
  - vendor/bin/phpunit --coverage-clover=build/coverage/clover.xml --coverage-text

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/coverage/clover.xml

notifications:
  email:
    - bjouhaud@gmail.com
